{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMCkBnVhBBKCI+aWHYJYB47",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Nirmal007160/CA-GITHUB-/blob/main/3.%20ID3%20decision%20tree.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import math\n",
        "\n",
        "class Node:\n",
        "    def __init__(self, attribute=None, value=None, results=None, true_branch=None,\n",
        "                 false_branch=None):\n",
        "        # Fix: Ensure correct unpacking by using line continuation or removing the comma\n",
        "        self.attribute, self.value, self.results, self.true_branch, self.false_branch = attribute, value, results, \\\n",
        "        true_branch, false_branch\n",
        "\n",
        "def build_tree(rows):\n",
        "    if not rows:\n",
        "        return Node()\n",
        "\n",
        "    # Check if all outcomes are the same (pure node)\n",
        "    if len(set(row[-1] for row in rows)) == 1:\n",
        "        return Node(results=rows[0][-1])\n",
        "\n",
        "    num_attributes = len(rows[0]) - 1 # Assuming the last column is the target variable\n",
        "\n",
        "    best_gain = 0.0\n",
        "    best_attribute_index = -1\n",
        "    best_split_value = None\n",
        "\n",
        "    for col in range(num_attributes):\n",
        "        # For simplicity, we are assuming categorical attributes and splitting on unique values\n",
        "        # A more robust decision tree might handle continuous values with thresholds\n",
        "        unique_values = set(row[col] for row in rows)\n",
        "\n",
        "        for value in unique_values:\n",
        "            # Split the data based on the attribute and value\n",
        "            true_rows = [row for row in rows if row[col] == value]\n",
        "            false_rows = [row for row in rows if row[col] != value]\n",
        "\n",
        "            if not true_rows or not false_rows:\n",
        "                continue\n",
        "\n",
        "            gain = information_gain(rows, col, value)\n",
        "\n",
        "            if gain > best_gain:\n",
        "                best_gain = gain\n",
        "                best_attribute_index = col\n",
        "                best_split_value = value\n",
        "\n",
        "    if best_gain == 0: # No gain, so it's a leaf node (or cannot be split further)\n",
        "        return Node(results=class_counts(rows)) # Return class counts for leaves that are not pure\n",
        "\n",
        "    true_rows = [row for row in rows if row[best_attribute_index] == best_split_value]\n",
        "    false_rows = [row for row in rows if row[best_attribute_index] != best_split_value]\n",
        "\n",
        "    true_branch = build_tree(true_rows)\n",
        "    false_branch = build_tree(false_rows)\n",
        "\n",
        "    return Node(attribute=best_attribute_index, value=best_split_value, true_branch=true_branch,\n",
        "                false_branch=false_branch)\n",
        "\n",
        "def information_gain(rows, col, value):\n",
        "    total_entropy = entropy(rows)\n",
        "\n",
        "    true_rows = [row for row in rows if row[col] == value]\n",
        "    false_rows = [row for row in rows if row[col] != value]\n",
        "\n",
        "    # Handle cases where a split results in an empty branch\n",
        "    if not true_rows or not false_rows:\n",
        "        return 0 # No gain if cannot split meaningfully\n",
        "\n",
        "    p_true = len(true_rows) / len(rows)\n",
        "    p_false = len(false_rows) / len(rows)\n",
        "\n",
        "    weighted_entropy = p_true * entropy(true_rows) + p_false * entropy(false_rows)\n",
        "\n",
        "    return total_entropy - weighted_entropy\n",
        "\n",
        "def entropy(rows):\n",
        "    if not rows:\n",
        "        return 0\n",
        "    counts = class_counts(rows)\n",
        "    total_rows = len(rows)\n",
        "    ent = 0.0\n",
        "    for count in counts.values():\n",
        "        p = count / total_rows\n",
        "        ent -= p * math.log2(p)\n",
        "    return ent\n",
        "\n",
        "def class_counts(rows):\n",
        "    # Fix: Correctly count occurrences of class labels, not entire rows\n",
        "    counts = {}\n",
        "    for row in rows:\n",
        "        label = row[-1]\n",
        "        counts[label] = counts.get(label, 0) + 1\n",
        "    return counts\n",
        "\n",
        "# Example dataset (you can modify this as needed)\n",
        "dataset = [\n",
        "    ['Sunny', 'Hot', 'High', 'Weak', 'No'],\n",
        "    ['Sunny', 'Hot', 'High', 'Strong', 'No'],\n",
        "    ['Overcast', 'Hot', 'High', 'Weak', 'Yes'],\n",
        "    ['Rain', 'Mild', 'High', 'Weak', 'Yes'],\n",
        "    ['Rain', 'Cool', 'Normal', 'Weak', 'Yes'],\n",
        "    ['Rain', 'Cool', 'Normal', 'Strong', 'No'],\n",
        "    ['Overcast', 'Cool', 'Normal', 'Strong', 'Yes'],\n",
        "    ['Sunny', 'Mild', 'High', 'Weak', 'No'],\n",
        "    ['Sunny', 'Cool', 'Normal', 'Weak', 'Yes'],\n",
        "    ['Rain', 'Mild', 'Normal', 'Weak', 'Yes']\n",
        "]\n",
        "\n",
        "# Build the decision tree\n",
        "tree = build_tree(dataset)\n",
        "\n",
        "# Print the decision tree\n",
        "def print_tree(node, indent=\"\"):\n",
        "    if node is None:\n",
        "        return\n",
        "\n",
        "    if node.results is not None:\n",
        "        print(indent + str(node.results))\n",
        "    else:\n",
        "        print(indent + f'Attribute {node.attribute} (value: {node.value})? ')\n",
        "        print(indent + '--> True:')\n",
        "        print_tree(node.true_branch, indent + '  ') # Increased indent for true branch\n",
        "        print(indent + '--> False:')\n",
        "        print_tree(node.false_branch, indent + '  ') # Increased indent for false branch\n",
        "\n",
        "print(\"Decision Tree:\")\n",
        "print_tree(tree)\n",
        "\n",
        "# Classify a new sample\n",
        "def classify(sample, node):\n",
        "    if node.results is not None:\n",
        "        # If it's a leaf node, return the result (which could be a single class or class counts)\n",
        "        if isinstance(node.results, dict):\n",
        "            # Return the class with the highest count if it's a dictionary of counts\n",
        "            return max(node.results, key=node.results.get)\n",
        "        else:\n",
        "            return node.results\n",
        "\n",
        "    # If it's an internal node, follow the appropriate branch\n",
        "    if sample[node.attribute] == node.value:\n",
        "        return classify(sample, node.true_branch)\n",
        "    else:\n",
        "        return classify(sample, node.false_branch)\n",
        "\n",
        "\n",
        "new_sample = ['Sunny', 'Cool', 'High', 'Strong']\n",
        "classification_result = classify(new_sample, tree)\n",
        "print(f\"\\nClassification result for {new_sample}: {classification_result}\")\n",
        "\n",
        "new_sample_2 = ['Sunny', 'Hot', 'High', 'Weak']\n",
        "classification_result_2 = classify(new_sample_2, tree)\n",
        "print(f\"Classification result for {new_sample_2}: {classification_result_2}\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "yV0yaMvChy2f",
        "outputId": "80155338-e1ad-4ee4-c224-494ba22efe50"
      },
      "execution_count": 13,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Decision Tree:\n",
            "Attribute 0 (value: Sunny)? \n",
            "--> True:\n",
            "  Attribute 1 (value: Cool)? \n",
            "  --> True:\n",
            "    Yes\n",
            "  --> False:\n",
            "    No\n",
            "--> False:\n",
            "  Attribute 3 (value: Weak)? \n",
            "  --> True:\n",
            "    Yes\n",
            "  --> False:\n",
            "    Attribute 0 (value: Rain)? \n",
            "    --> True:\n",
            "      No\n",
            "    --> False:\n",
            "      Yes\n",
            "\n",
            "Classification result for ['Sunny', 'Cool', 'High', 'Strong']: Yes\n",
            "Classification result for ['Sunny', 'Hot', 'High', 'Weak']: No\n"
          ]
        }
      ]
    }
  ]
}